# permissions for end users to edit directuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: directus-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: directus-operator
    app.kubernetes.io/part-of: directus-operator
    app.kubernetes.io/managed-by: kustomize
  name: directus-editor-role
rules:
- apiGroups:
  - apps.directus.io
  resources:
  - directuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.directus.io
  resources:
  - directuses/status
  verbs:
  - get
